apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-secret-sync.fullname" . }}
  labels: {{- include "kube-secret-sync.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - 'kube-secret-sync.io'
    resources:
      - secretsyncrules
    verbs:
      - get
      - list
      - watch
