apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-secret-sync
  namespace: kube-secret-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: kube-secret-sync
  name: kube-secret-sync
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - list
      - create
      - get
      - delete
      - watch
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-secret-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-secret-sync
subjects:
  - kind: ServiceAccount
    name: kube-secret-sync
    namespace: kube-secret-sync
