//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/alehechka/kube-secret-sync/api/types"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceRules) DeepCopyInto(out *NamespaceRules) {
	*out = *in
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make(types.StringSlice, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeRegex != nil {
		in, out := &in.ExcludeRegex, &out.ExcludeRegex
		*out = make(types.StringSlice, len(*in))
		copy(*out, *in)
	}
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make(types.StringSlice, len(*in))
		copy(*out, *in)
	}
	if in.IncludeRegex != nil {
		in, out := &in.IncludeRegex, &out.IncludeRegex
		*out = make(types.StringSlice, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceRules.
func (in *NamespaceRules) DeepCopy() *NamespaceRules {
	if in == nil {
		return nil
	}
	out := new(NamespaceRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rules) DeepCopyInto(out *Rules) {
	*out = *in
	in.Namespaces.DeepCopyInto(&out.Namespaces)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rules.
func (in *Rules) DeepCopy() *Rules {
	if in == nil {
		return nil
	}
	out := new(Rules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Secret) DeepCopyInto(out *Secret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Secret.
func (in *Secret) DeepCopy() *Secret {
	if in == nil {
		return nil
	}
	out := new(Secret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSyncRule) DeepCopyInto(out *SecretSyncRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSyncRule.
func (in *SecretSyncRule) DeepCopy() *SecretSyncRule {
	if in == nil {
		return nil
	}
	out := new(SecretSyncRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretSyncRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSyncRuleList) DeepCopyInto(out *SecretSyncRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretSyncRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSyncRuleList.
func (in *SecretSyncRuleList) DeepCopy() *SecretSyncRuleList {
	if in == nil {
		return nil
	}
	out := new(SecretSyncRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretSyncRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSyncRuleSpec) DeepCopyInto(out *SecretSyncRuleSpec) {
	*out = *in
	out.Secret = in.Secret
	in.Rules.DeepCopyInto(&out.Rules)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSyncRuleSpec.
func (in *SecretSyncRuleSpec) DeepCopy() *SecretSyncRuleSpec {
	if in == nil {
		return nil
	}
	out := new(SecretSyncRuleSpec)
	in.DeepCopyInto(out)
	return out
}
