apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretsyncrules.kube-secret-sync.io
  labels: {{- include "kube-secret-sync.labels" . | nindent 4 }}
spec:
  group: kube-secret-sync.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secret:
                  type: string
                namespace:
                  type: string
                rules:
                  type: object
                  properties:
                    namespaces:
                      type: object
                      properties:
                        exclude:
                          type: array
                          items:
                            type: string
                        excludeRegex:
                          type: array
                          items:
                            type: string
                        include:
                          type: array
                          items:
                            type: string
                        includeRegex:
                          type: array
                          items:
                            type: string
                    force:
                      type: boolean
  scope: Cluster
  names:
    plural: secretsyncrules
    singular: secretsyncrule
    kind: SecretSyncRule
    categories:
      - kube-secret-sync
