name: Pull Request Verification

on:
  pull_request:

jobs:
  pr:
    name: Pull Request Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies
        run: go mod download

      - name: Build Executable
        run: go build cmd/kube-secret-sync/main.go

      - name: Run unit tests
        run: go test ./... --cover

      - name: Build Docker image
        run: docker build -t kube-secret-sync .
